enum AppRoute {
  login('/login'),
  changePassword('/change-password'),
  adminDashboard('/admin-dashboard'),
  directorDashboard('/director-dashboard'),
  principalDashboard('/principal-dashboard'),
  teacherDashboard('/teacher-dashboard'),
  parentDashboard('/parent-dashboard'),
  studentDashboard('/student-dashboard'),
  students('/students'),
  teachers('/teachers'),
  classes('/academic-structure/classes'),
  sections('/academic-structure/sections'),
  subjects('/academic-structure/subjects'),
  addStudent('/students/add'),
  studentSearch('/students/search'),
  studentClasses('/students/classes'),
  studentClassSections('/students/classes/:classId/sections'),
  studentList('/students/classes/:classId/sections/:sectionId'),
  studentDetails('/students/:studentId'),
  editStudent('/students/:studentId/edit'),
  fees('/fees'),
  feeSearch('/fees/search'),
  feeStudentLedger('/fees/students/:studentId'),
  homework('/homework'),
  timetable('/timetable'),
  exams('/exams'),
  addExam('/exams/add'),
  editExam('/exams/:examId/edit'),
  examSubjects('/exams/:examId/subjects'),
  examResults('/exams/:examId/results'),
  examReportCard('/exams/:examId/results/:studentId'),
  transportDashboard('/transport'),
  vehicles('/transport/vehicles'),
  routes('/transport/routes'),
  certificates('/certificates'),
  addCertificate('/certificates/add'),
  certificateDetails('/certificates/:certificateId'),
  notFound('/not-found');

  const AppRoute(this.path);

  final String path;
}
